services:
  liss-tv:
    image: liss-tv:latest
    container_name: liss-tv
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        - NEXT_PUBLIC_POCKETBASE_URL=https://pocketbase.isaacdev.site
    ports:
      - "8000:8000"
